apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service-deployment
  labels:
    app: posts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
      - name: posts-service
        image: <YOUR_DOCKERHUB_USERNAME>/flaskblog-posts-service:latest
        ports:
        - containerPort: 5000
