apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=  # This is "password" encoded in base64. Change this to your actual password encoded in base64.
